apiVersion: v1
kind: Secret
metadata:
  name: minirtos-postgres-secret
  namespace: minirtos
  labels:
    app.kubernetes.io/name: minirtos-postgres
type: Opaque
stringData:
  POSTGRES_DB: minirtos_playground
  POSTGRES_USER: minirtos
  POSTGRES_PASSWORD: minirtos
