apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 00-namespace.yml
  - 01-postgres-secret.yml
  - 02-backend-configmap.yml
  - 03-postgres-statefulset.yml
  - 04-backend-deployment.yml
  - 05-frontend-deployment.yml
