apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minirtos-ingress
  namespace: minirtos
  labels:
    app.kubernetes.io/name: minirtos-ingress
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: minirtos-backend
                port:
                  number: 8081
          - path: /
            pathType: Prefix
            backend:
              service:
                name: minirtos-frontend
                port:
                  number: 80
