FROM maven:3.9.9-eclipse-temurin-17 AS build

WORKDIR /app

COPY backend/pom.xml backend/pom.xml
COPY backend/src backend/src

WORKDIR /app/backend

RUN mvn -q -DskipTests package

FROM eclipse-temurin:17-jre

WORKDIR /app

COPY --from=build /app/backend/target/minirtos-playground-backend.jar app.jar

EXPOSE 8081

ENTRYPOINT ["java", "-jar", "app.jar"]
