apiVersion: apps/v1
kind: Deployment
metadata:
  name: minirtos-frontend
  namespace: minirtos
spec:
  template:
    spec:
      containers:
        - name: frontend
          image: ghcr.io/amanahmed2002/minirtos-linux/frontend:latest
          imagePullPolicy: Always
